In [7]:
import numpy as np
numpy_array = np.array([2, 4, 12])

type(numpy_array)


multiplicados_array = numpy_array * 3
multiplicados_array




array([ 6, 12, 36])

In [8]:
[2, 4, 12] *3

[2, 4, 12, 2, 4, 12, 2, 4, 12]

In [9]:
multiplicados_array.shape

(3,)

In [11]:
multiplicados_array.dtype

dtype('int64')

In [12]:
# generamos un array de 1000000 observaciones con `np.arange`
n_sims = 1000000
demo_array = np.arange(n_sims)

# generamos un objeto range y posteriormente lo pasamos a formato lista
demo_list = list(range(n_sims))

In [2]:
import numpy as np
array_strings = np.array(["gata","perro","erizo"])

In [3]:
type(array_strings)

numpy.ndarray

In [4]:
mixto = np.array(["gato", 1, 2.8])

In [6]:
type(mixto)

numpy.ndarray

In [7]:
import  pandas as pd
df= pd.read_csv("nations.csv")

In [8]:
type(df.values)

numpy.ndarray

In [12]:
import  pandas as pd
import numpy as np
df= pd.read_csv("nations.csv")
type(df["gdp"].values)


numpy.ndarray

In [13]:
datos_aleatorios =np.random.randn(4,4)

In [14]:
datos_aleatorios

array([[-0.99461726, -1.4109856 , -1.16174656,  1.79695727],
       [ 0.62416957,  0.33734526,  0.63030541,  0.99972967],
       [ 0.74695278,  2.3620274 ,  0.11872243,  1.36419538],
       [-0.92085277, -0.90778085,  0.22418204, -0.78108405]])

In [15]:
import numpy as np
secuencia = np.arange(10)
secuencia[3]

3

In [16]:
secuencia[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
secuencia[7:]

array([7, 8, 9])

In [18]:
secuencia[:5]

array([0, 1, 2, 3, 4])

In [19]:
sub_secuencia = secuencia[5:9]

In [21]:
sub_secuencia[0] = 13213

In [23]:
sub_secuencia

array([13213,     6,     7,     8])

In [24]:
secuencia

array([    0,     1,     2,     3,     4, 13213,     6,     7,     8,
           9])

In [25]:
df.values

array([[1, 'Algeria', 'Africa', ..., 72.5999984741211, 15.0, nan],
       [2, 'Benin', 'Africa', ..., 41.7000007629395, 1.20000004768372,
        nan],
       [3, 'Botswana', 'Africa', ..., 84.0999984741211, 9.19999980926514,
        nan],
       ...,
       [192, 'Tonga', 'Oceania', ..., 99.0, 4.850000381469731, nan],
       [193, 'Tuvalu', 'Oceania', ..., nan, nan, nan],
       [194, 'Vanuatu', 'Oceania', ..., 82.0, 1.5, nan]], dtype=object)

In [26]:
df.head()

Unnamed: 0       country  region           gdp    school      adfert  \
0           1       Algeria  Africa   7300.399902  6.716667    7.300000   
1           2         Benin  Africa   1338.800049  3.100000  111.699997   
2           3      Botswana  Africa  12307.400391  8.600000   52.099998   
3           4  Burkina Faso  Africa   1063.400024  1.300000  124.800003   
4           5       Burundi  Africa    349.200012  2.483333   18.600000   

   chldmort       life       pop      urban  femlab   literacy   co2  \
0     34.75  72.316666  34172236  64.933334  0.4522  72.599998  15.0   
1    122.75  54.733334   8237634  41.000000  0.8482  41.700001   1.2   
2     60.25  52.250000   1941233  59.250000  0.8870  84.099998   9.2   
3    170.50  53.783333  15308383  23.583334  0.8584  23.600000   0.2   
4    168.50  48.866665   7821783  10.250000  1.0344  66.599998   0.1   

        gini  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4  33.299999

In [27]:
matrix =np.array([[0,1,2],[3,4,5],[6,7,8]])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
matrix[2]

array([6, 7, 8])

In [29]:
matrix[2][1]

7

In [31]:
matrix[2, 1]

7

In [32]:
matrix2[:2]

NameError: name 'matrix2' is not defined

In [33]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
matrix[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
matrix[:2, 1:]

array([[1, 2],
       [4, 5]])

In [36]:
matrix[:1]

array([[0, 1, 2]])

In [45]:
import numpy as np
nombres = np.array(["sebastian","pedro","Maria","Fernanda"])
notass = np.array([[5,5,6], [6,6,7], [7,7,6], [5,4,6]])


In [46]:
nombres == "pedro"

array([False,  True, False, False])

In [48]:
notass[nombres == "pedro"]

array([[6, 6, 7]])

In [49]:
notass[~(nombres == "pedro")]

array([[5, 5, 6],
       [7, 7, 6],
       [5, 4, 6]])

In [50]:
array_30 = np.arange(30)
array_30

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
redminesionado = array_30.reshape((5,6))

In [52]:
redminesionado

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [54]:
redminesionado.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [55]:
redminesionado


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [57]:
array_funciones = np.array([2, 9, 15, 25])

np.sqrt(array_funciones)

array([1.41421356, 3.        , 3.87298335, 5.        ])

In [59]:
notas = np.array([4.5, 6.6, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 6.8, 5.0])
notas_bin = np.where(notas >= notas.mean(), 1 , 0)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [60]:
notas.mean()

6.536363636363637